---
title: "HW4"
author: "Max Russer"
date: "May 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

data <- read_csv("HW4Data.csv")

```

```{r}
#Part 1.

lm_A <- lm(MC_A ~ Abatement, data = data)
lm_A

lm_B <- lm(MC_B ~ Abatement, data = data)
lm_B

lm_C <- lm(MC_C ~ Abatement, data = data)
lm_C

lm_D <- lm(MC_D ~ Abatement, data = data)
lm_D

#still need plots

```


```{r}
#Part 2. 

#need to plug in each sector's emissions into their respective linear models to find intercept
#need to find the slope of the MB for each sector using their respective emissions
#we can use these to find the demand curve

#Sector A

-8.6445 + 0.5768 * 180

A_dem <- function(x) 95.1795 - 0.528775 * x

A_dem_plot <- ggplot(data.frame(x = c(70000, 500000), y = c(0, 30)),aes(x = x, y = y)) +
  stat_function(fun = A_dem, geom = "line", color = "blue") +
  scale_x_continuous(expand = c(0,0), limits = c(0,200)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,100))

A_dem_plot




```





